apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod
spec:
  restartPolicy: OnFailure # Options are Always, OnFailure, and Never
  containers:
    - name: nvidia-smi
      image: nvidia/cuda:9.0-base
      command: ["nvidia-smi"]
      resources:
        limits:
          nvidia.com/gpu: 1 # requesting 2 GPUs