apiVersion: batch/v1 # Default K8 API
kind: Job # This tells kubernetes what kind of class it is working with
metadata:
  name: hello-world # Name of the Job
spec:
  template: # Pod Templete
    spec:
      containers:
      restartPolicy: OnFailure # Options are Always, OnFailure, and Never.
      - name: hello-world # Container name (Can be set to whatever)
        image: hello-world:latest # Docker Image hosted on Docker Hub