apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod
spec:
  containers:
    restartPolicy: OnFailure # Options are Always, OnFailure, and Never
    - name: nvidia-smi
      image: nvidia/cuda:9.0-base
      resources:
        limits:
          nvidia.com/gpu: 1 # requesting 2 GPUs