apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod
spec:
  containers:
    - name: nvidia-smi
      image: nvidia/cuda:9.0-base nvidia-smi
      resources:
        limits:
          nvidia.com/gpu: 1 # requesting 2 GPUs