apiVersion: v1 # Default K8 API
kind: Pod # This tells kubernetes what kind of class it is working with
metadata:
  name: pytorch-jupyter # Name of the Pod
  labels:
    app: jupyter-notebook-synicix
spec:
  restartPolicy: OnFailure # Options are Always, OnFailure, and Never
  containers:
  - name: pytorch-jupyter # Container name (Can be set to whatever)
    image: synicix/pytorch-jupyter # Docker Image hosted on Docker Hub
    command: ["mkdir notebooks", "cd notebooks"]
    volumesMounts:
      name: scratch07
      - mountPath: "/notebook/scratch07"
    ports:
    - containerPort: 8888
  volumes:
    - name: scratch07-claim
    persistentVolumeClaim:
      claimName: test-claim