kind: Service
apiVersion: v1
metadata:
  name: synicix-jupyter-notebook
spec:
  type: NodePort
  selector:
    app: jupyter-notebook-synicix
  ports:
  - protocol: TCP
    nodePort: 30040
    port: 8888
    targetPort: 8888