apiVersion: batch/v1 # Jobs Default K8 API
kind: Job # This tells kubernetes what kind of class it is working with
metadata:
  name: nvidia-job # Name of the Job
spec:
  completions: 5
  parallelism: 5
  template: # Pod Templete
    spec:
      restartPolicy: OnFailure # Options are Always, OnFailure, and Never.
      containers:
      - name: nvidia-smi
        image: nvidia/cuda:9.0-base
        command: ["nvidia-smi"]
        resources:
          limits:
            nvidia.com/gpu: 1 # requesting 2 GPUs