apiVersion: v1 # Default K8 API
kind: Pod # This tells kubernetes what kind of class it is working with
metadata:
  name: redis # Name of the Pod
spec:
  restartPolicy: OnFailure # Options are Always, OnFailure, and Never
  containers:
  - name: redis # Container name (Can be set to whatever)
    image: redis
    env:
      - name: USERNAME
        valueFrom:
          secretKeyRef:
            name: mysecret
            key: username
      - name: PASSWORD
        valueFrom:
          secretKeyRef:
            name: mysecret
            key: password